# Generated by Django 4.2.7 on 2024-01-02 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartdataorganizer_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='spreadsheet',
            name='date_uploaded',
        ),
        migrations.AlterField(
            model_name='spreadsheet',
            name='file',
            field=models.FileField(upload_to='spreadsheets/'),
        ),
        migrations.AlterField(
            model_name='spreadsheet',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
