# Generated by Django 4.2.7 on 2024-01-02 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smartdataorganizer_app', '0002_remove_spreadsheet_date_uploaded_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='spreadsheet',
            name='name',
        ),
    ]
